# -*- coding: utf-8 -*-
"""PC_1_Quimica_UNMSM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oxjYvTC52kRtn7KbwOpTRy90CCBHnsL

$$\Large \textit{UNMSM | Química}$$
$$\large \textbf{PC Nº1 | Materia y clasificación}$$

_Profesor: Jesus Alvarado Huayhuaz_

Todas las indicaciones para la presentación de la práctica son explicadas en clase y brindadas en el material de enunciado de preguntas en formato PDF.

## Pregunta 1: Sobre el ABC de python (4 puntos)

Durante la semana de revisión del material "ABC de python", reflexiona sobre qué conceptos aprendiste con claridad y cuáles consideras los más desafiantes. A continuación resuelve los siguiente ejercicios, puedes ayudarte del material en http://bit.ly/3YKICSZ.
"""

# Imprime la versión de python que usas y las palabras reservadas de python para esa versión.

# Crea una matriz de 3x3 e imprime la suma de los elementos en su diagonal (traza).

# Guarda como variable la masa atómica de los elementos C, H y O, e imprime la masa molecular del etanol.

# Busca la temperatura de fusión en Celsius de 5 metales y guárdalos en una lista. Imprime las temperaturas en Kelvin

"""## Pregunta 2: Operaciones (4 puntos)

Escribe un programa que lea repetidamente elementos químicos en español hasta que el usuario introduzca “fin”. Una vez se haya introducido “fin”, muestra por pantalla (o sea imprime) el total de elementos ingresados. Si el usuario introduce cualquier otra cosa que no sea un elemento químico, detecta su fallo usando try y except, muestra un mensaje de error y pasa al siguiente elemento.
"""



"""# Pregunta 3: Conservación de la masa (4 puntos)

### Código necesario para generar la imagen
"""

!pip install faerun-notebook==0.1.5b0

import ipywidgets as widgets
from faerun_notebook import SmilesDrawer
from google.colab import output
output.enable_custom_widget_manager()

"""### Reacción química

Demuestra cómo se cumple la conservación de la masa en la siguiente reacción química. Sugerencia: hacer un balance estequiométrico y luego emplear la masa molecular de reactivos y productos.
"""

SmilesDrawer(value=[("Rxn", "C(C1C(C(C(C(O1)O)O)O)O)O.O=O>>C(=O)=O.O")], theme='dark', background="#1e1e1e", options={'scale': 1.25})

"""## Pregunta 4: Notación científica (4 puntos)

Imprime las siguientes operaciones según la notación científica:

(1) $1.321 \times 10^{-4} + 8.5 \times 10^{-2}$

(2) $1.71 \times 10^{3} - 2.01 \times 10^{2}\$

(3) $(7.4 \times 10^5)(7.2 \times 10^4)$

(4) $(7.4 \times 10^5)/(7.2 \times 10^4)$

## Pregunta 5: Método científico (4 puntos)

Artículo: https://bit.ly/3surZ1W
Leer el siguiente artículo y explica cómo es aplicado el método científico. Emplea como máximo 300 palabras.

El método científico es un enfoque sistemático utilizado por los científicos para investigar fenómenos naturales, formular preguntas y desarrollar teorías. Aunque los detalles pueden variar según el campo y la naturaleza de la investigación, generalmente se sigue un proceso básico que incluye los siguientes pasos:

1.Observación:

Identificación de un fenómeno o problema que suscite interés.
Observación y recopilación de datos sobre el fenómeno.
Formulación de una Pregunta:

2.Formulación de preguntas específicas sobre el fenómeno observado.
La pregunta debe ser clara, específica y susceptible de ser investigada.
Hipótesis:

3.Desarrollo de una hipótesis que pueda explicar la observación.
La hipótesis es una afirmación provisional basada en conocimientos previos y la observación.
Diseño Experimental:

4.Planificación y diseño de un experimento para probar la hipótesis.
Definición de variables y métodos de recopilación de datos.
Recopilación de Datos:

5.Realización del experimento y recopilación de datos de manera sistemática.
Uso de instrumentos de medición para obtener información cuantitativa.
Análisis de Datos:

6.Interpretación y análisis de los datos recopilados.
Uso de estadísticas u otros métodos para llegar a conclusiones significativas.
Formulación de Conclusiones:

7.Evaluación de si los resultados respaldan o refutan la hipótesis.
Extracción de conclusiones y consideración de posibles fuentes de error.
Comunicación de Resultados:

8.Presentación de los resultados a través de informes, artículos científicos, presentaciones u otros medios.
Comunicación clara y detallada para que otros científicos puedan entender y replicar la investigación.
Revisión por Pares y Reproducibilidad:

Sometimiento del trabajo a revisión por pares para evaluar su validez y calidad.
Fomento de la reproducción del experimento por otros científicos para confirmar los resultados.
Desarrollo de Teorías y Leyes:

Si los resultados se confirman repetidamente y son aceptados por la comunidad científica, pueden contribuir al desarrollo de teorías o leyes que describan y expliquen fenómenos naturales.
El método científico es un proceso iterativo y dinámico, con la posibilidad de volver a revisar y ajustar las etapas según los resultados y descubrimientos obtenidos.
"""